/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    leads: Lead;
    projects: Project;
    promotions: Promotion;
    posts: Post;
    'progress-updates': ProgressUpdate;
    jobs: Job;
    'job-applications': JobApplication;
    'cv-files': CvFile;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'progress-updates': ProgressUpdatesSelect<false> | ProgressUpdatesSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    'cv-files': CvFilesSelect<false> | CvFilesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('th' | 'en') | ('th' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'th' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Build pages with blocks. Homepage uses slug = home
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * home = หน้าแรก · อื่นๆ เช่น about → northland.co.th/about
   */
  slug: string;
  layout?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            tagline?: string | null;
            lead?: string | null;
            /**
             * เลือกหลายรูปเพื่อทำสไลด์โชว์ · ถ้าไม่เลือก จะใช้รูปเดี่ยว/ลิงก์ด้านล่างแทน
             */
            bgImages?: (number | Media)[] | null;
            image?: (number | null) | Media;
            /**
             * ใช้เมื่อไม่มีรูปสไลด์ เช่น /wp/BG.jpg
             */
            imageUrl?: string | null;
            heroAutoplay?: boolean | null;
            heroInterval?: number | null;
            /**
             * พิมพ์: fade (จางเข้า-ออก) หรือ slide (เลื่อน)
             */
            heroTransition?: string | null;
            buttons?:
              | {
                  label: string;
                  /**
                   * เช่น /projects หรือ /contact
                   */
                  url: string;
                  style?: ('primary' | 'light' | 'ghost' | 'outline-white') | null;
                  id?: string | null;
                }[]
              | null;
            showSearch?: boolean | null;
            eyebrowFont?: string | null;
            eyebrowWeight?: string | null;
            eyebrowSize?: string | null;
            eyebrowColor?: string | null;
            titleFont?: string | null;
            titleWeight?: string | null;
            titleSize?: string | null;
            titleColor?: string | null;
            taglineFont?: string | null;
            taglineWeight?: string | null;
            taglineSize?: string | null;
            taglineColor?: string | null;
            leadFont?: string | null;
            leadWeight?: string | null;
            leadSize?: string | null;
            leadColor?: string | null;
            background?: ('none' | 'soft' | 'brand' | 'dark' | 'custom' | 'image') | null;
            paddingY?: ('sm' | 'md' | 'lg') | null;
            bgColor?: string | null;
            textOnDark?: boolean | null;
            bgImage?: (number | null) | Media;
            marginTop?: string | null;
            marginBottom?: string | null;
            paddingX?: string | null;
            gap?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            items?:
              | {
                  /**
                   * เช่น 30+, 3,209, 8,110
                   */
                  number: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            background?: ('none' | 'soft' | 'brand' | 'dark' | 'custom' | 'image') | null;
            paddingY?: ('sm' | 'md' | 'lg') | null;
            bgColor?: string | null;
            textOnDark?: boolean | null;
            bgImage?: (number | null) | Media;
            marginTop?: string | null;
            marginBottom?: string | null;
            paddingX?: string | null;
            gap?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            subtitle?: string | null;
            headingAlign?: ('left' | 'center' | 'right') | null;
            source?: ('manual' | 'featured' | 'latest') | null;
            /**
             * ค้นหาแล้วเลือกโครงการที่ต้องการ — เรียงลำดับตามที่เลือก
             */
            projects?: (number | Project)[] | null;
            count?: number | null;
            /**
             * เช่น ดูโครงการทั้งหมด →
             */
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            columns?: ('1' | '2' | '3' | '4' | '5') | null;
            eyebrowFont?: string | null;
            eyebrowWeight?: string | null;
            eyebrowSize?: string | null;
            eyebrowColor?: string | null;
            headingFont?: string | null;
            headingWeight?: string | null;
            headingSize?: string | null;
            headingColor?: string | null;
            subtitleFont?: string | null;
            subtitleWeight?: string | null;
            subtitleSize?: string | null;
            subtitleColor?: string | null;
            background?: ('none' | 'soft' | 'brand' | 'dark' | 'custom' | 'image') | null;
            paddingY?: ('sm' | 'md' | 'lg') | null;
            bgColor?: string | null;
            textOnDark?: boolean | null;
            bgImage?: (number | null) | Media;
            marginTop?: string | null;
            marginBottom?: string | null;
            paddingX?: string | null;
            gap?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredProjects';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            subtitle?: string | null;
            columns?: ('1' | '2' | '3' | '4' | '5') | null;
            items?:
              | {
                  /**
                   * เช่น 🏆 🏗️ 📍 💎
                   */
                  icon?: string | null;
                  title: string;
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            eyebrowFont?: string | null;
            eyebrowWeight?: string | null;
            eyebrowSize?: string | null;
            eyebrowColor?: string | null;
            headingFont?: string | null;
            headingWeight?: string | null;
            headingSize?: string | null;
            headingColor?: string | null;
            subtitleFont?: string | null;
            subtitleWeight?: string | null;
            subtitleSize?: string | null;
            subtitleColor?: string | null;
            background?: ('none' | 'soft' | 'brand' | 'dark' | 'custom' | 'image') | null;
            paddingY?: ('sm' | 'md' | 'lg') | null;
            bgColor?: string | null;
            textOnDark?: boolean | null;
            bgImage?: (number | null) | Media;
            marginTop?: string | null;
            marginBottom?: string | null;
            paddingX?: string | null;
            gap?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            align?: ('left' | 'center') | null;
            width?: ('narrow' | 'normal') | null;
            eyebrowFont?: string | null;
            eyebrowWeight?: string | null;
            eyebrowSize?: string | null;
            eyebrowColor?: string | null;
            headingFont?: string | null;
            headingWeight?: string | null;
            headingSize?: string | null;
            headingColor?: string | null;
            background?: ('none' | 'soft' | 'brand' | 'dark' | 'custom' | 'image') | null;
            paddingY?: ('sm' | 'md' | 'lg') | null;
            bgColor?: string | null;
            textOnDark?: boolean | null;
            bgImage?: (number | null) | Media;
            marginTop?: string | null;
            marginBottom?: string | null;
            paddingX?: string | null;
            gap?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image?: (number | null) | Media;
            /**
             * ใช้แทนการอัปโหลด เช่น /wp/ARNA.jpg
             */
            imageUrl?: string | null;
            imageSide?: ('left' | 'right') | null;
            eyebrow?: string | null;
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            buttons?:
              | {
                  label: string;
                  /**
                   * เช่น /projects หรือ /contact
                   */
                  url: string;
                  style?: ('primary' | 'light' | 'ghost' | 'outline-white') | null;
                  id?: string | null;
                }[]
              | null;
            eyebrowFont?: string | null;
            eyebrowWeight?: string | null;
            eyebrowSize?: string | null;
            eyebrowColor?: string | null;
            headingFont?: string | null;
            headingWeight?: string | null;
            headingSize?: string | null;
            headingColor?: string | null;
            background?: ('none' | 'soft' | 'brand' | 'dark' | 'custom' | 'image') | null;
            paddingY?: ('sm' | 'md' | 'lg') | null;
            bgColor?: string | null;
            textOnDark?: boolean | null;
            bgImage?: (number | null) | Media;
            marginTop?: string | null;
            marginBottom?: string | null;
            paddingX?: string | null;
            gap?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            heading?: string | null;
            cols?:
              | {
                  /**
                   * เลขมาก = กว้างกว่า (เช่น 2 กับ 1 = 2 ส่วนต่อ 1 ส่วน)
                   */
                  span?: number | null;
                  image?: (number | null) | Media;
                  imageUrl?: string | null;
                  colHeading?: string | null;
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  headingFont?: string | null;
                  headingColor?: string | null;
                  align?: ('left' | 'center') | null;
                  id?: string | null;
                }[]
              | null;
            valign?: ('top' | 'center') | null;
            headingFont?: string | null;
            headingWeight?: string | null;
            headingSize?: string | null;
            headingColor?: string | null;
            background?: ('none' | 'soft' | 'brand' | 'dark' | 'custom' | 'image') | null;
            paddingY?: ('sm' | 'md' | 'lg') | null;
            bgColor?: string | null;
            textOnDark?: boolean | null;
            bgImage?: (number | null) | Media;
            marginTop?: string | null;
            marginBottom?: string | null;
            paddingX?: string | null;
            gap?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'columns';
          }
        | {
            heading?: string | null;
            columns?: ('1' | '2' | '3' | '4' | '5') | null;
            /**
             * กดเลือกได้หลายรูปในครั้งเดียว
             */
            imageList?: (number | Media)[] | null;
            headingFont?: string | null;
            headingWeight?: string | null;
            headingSize?: string | null;
            headingColor?: string | null;
            background?: ('none' | 'soft' | 'brand' | 'dark' | 'custom' | 'image') | null;
            paddingY?: ('sm' | 'md' | 'lg') | null;
            bgColor?: string | null;
            textOnDark?: boolean | null;
            bgImage?: (number | null) | Media;
            marginTop?: string | null;
            marginBottom?: string | null;
            paddingX?: string | null;
            gap?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            /**
             * กดเลือกได้หลายรูปในครั้งเดียว
             */
            imageList?: (number | Media)[] | null;
            autoplay?: boolean | null;
            height?: ('sm' | 'md' | 'lg') | null;
            headingFont?: string | null;
            headingWeight?: string | null;
            headingSize?: string | null;
            headingColor?: string | null;
            background?: ('none' | 'soft' | 'brand' | 'dark' | 'custom' | 'image') | null;
            paddingY?: ('sm' | 'md' | 'lg') | null;
            bgColor?: string | null;
            textOnDark?: boolean | null;
            bgImage?: (number | null) | Media;
            marginTop?: string | null;
            marginBottom?: string | null;
            paddingX?: string | null;
            gap?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slider';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            subtitle?: string | null;
            items?:
              | {
                  year: string;
                  title: string;
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            eyebrowFont?: string | null;
            eyebrowWeight?: string | null;
            eyebrowSize?: string | null;
            eyebrowColor?: string | null;
            headingFont?: string | null;
            headingWeight?: string | null;
            headingSize?: string | null;
            headingColor?: string | null;
            subtitleFont?: string | null;
            subtitleWeight?: string | null;
            subtitleSize?: string | null;
            subtitleColor?: string | null;
            background?: ('none' | 'soft' | 'brand' | 'dark' | 'custom' | 'image') | null;
            paddingY?: ('sm' | 'md' | 'lg') | null;
            bgColor?: string | null;
            textOnDark?: boolean | null;
            bgImage?: (number | null) | Media;
            marginTop?: string | null;
            marginBottom?: string | null;
            paddingX?: string | null;
            gap?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            title: string;
            text?: string | null;
            buttons?:
              | {
                  label: string;
                  /**
                   * เช่น /projects หรือ /contact
                   */
                  url: string;
                  style?: ('primary' | 'light' | 'ghost' | 'outline-white') | null;
                  id?: string | null;
                }[]
              | null;
            titleFont?: string | null;
            titleWeight?: string | null;
            titleSize?: string | null;
            titleColor?: string | null;
            textFont?: string | null;
            textWeight?: string | null;
            textSize?: string | null;
            textColor?: string | null;
            background?: ('none' | 'soft' | 'brand' | 'dark' | 'custom' | 'image') | null;
            paddingY?: ('sm' | 'md' | 'lg') | null;
            bgColor?: string | null;
            textOnDark?: boolean | null;
            bgImage?: (number | null) | Media;
            marginTop?: string | null;
            marginBottom?: string | null;
            paddingX?: string | null;
            gap?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            size?: ('sm' | 'md' | 'lg') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spacer';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Image library — 3 sizes generated automatically
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * All projects — save as draft until ready to publish
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * เช่น Attaluck สุขุมวิท
   */
  title: string;
  /**
   * ภาษาอังกฤษตัวเล็ก คั่นด้วยขีด เช่น attaluck-sukhumvit
   */
  slug: string;
  category: 'single-house' | 'pool-villa' | 'townhome' | 'condo' | 'commercial';
  status: 'coming-soon' | 'under-construction' | 'ready' | 'sold-out';
  zone: 'bangkok' | 'saraburi';
  /**
   * เช่น ซอยสุขุมวิท 50, แขวงพระโขนง, กรุงเทพฯ
   */
  address?: string | null;
  /**
   * เช่น Private Sanctuary in the Heart of Sukhumvit
   */
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  specs?: {
    units?: string | null;
    usableArea?: string | null;
    landSize?: string | null;
    bedrooms?: string | null;
    bathrooms?: string | null;
    projectValue?: string | null;
  };
  /**
   * เช่น 68 ล้านบาท
   */
  startingPrice?: string | null;
  priceTier?: ('low' | 'mid' | 'high' | 'luxury') | null;
  /**
   * เช่น ผ่อนดาวน์ 0% สูงสุด 24 เดือน · รับสิทธิ์โอนฟรี
   */
  promoNote?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * เลือก "ตามรูปจริง" ถ้าไม่อยากให้โดนครอป
   */
  coverAspect?: ('auto' | '16-9' | '21-9' | '4-3' | '1-1' | '3-4') | null;
  coverFit?: ('cover' | 'contain') | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  floorPlans?:
    | {
        /**
         * เช่น แบบบ้าน Type A / ผังโครงการ
         */
        name: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  map?: {
    /**
     * กดปุ่ม Share ใน Google Maps แล้วคัดลอกลิงก์มาวาง
     */
    googleMapsUrl?: string | null;
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * เว้นว่าง = ใช้เบอร์/LINE กลางของบริษัท
   */
  contact?: {
    phone?: string | null;
    lineId?: string | null;
    salesEmail?: string | null;
  };
  videoUrl?: string | null;
  virtualTourUrl?: string | null;
  locationFeatures?:
    | {
        /**
         * เช่น การเดินทาง / ไลฟ์สไตล์ / โรงพยาบาล / โรงเรียน
         */
        title: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * เลขน้อยแสดงก่อน
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Leads from the website contact form — newest first
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  interestProject?: (number | null) | Project;
  interestText?: string | null;
  budget?: ('under-3m' | '3-7m' | '7-20m' | '20m-up') | null;
  message?: string | null;
  consentPDPA: boolean;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Promotions auto-hide from the website after the end date
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  title: string;
  image?: (number | null) | Media;
  /**
   * เว้นว่างได้ถ้าเป็นโปรรวมทุกโครงการ
   */
  project?: (number | null) | Project;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  startDate: string;
  /**
   * เว้นว่าง = ไม่มีวันหมดเขต
   */
  endDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Articles and news — draft until ready to publish
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * ภาษาอังกฤษตัวเล็ก คั่นด้วยขีด เช่น how-to-choose-home-loan
   */
  slug: string;
  coverImage?: (number | null) | Media;
  category: 'news' | 'knowledge' | 'lifestyle';
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * ตั้งวันที่ในอนาคตได้ — บทความจะขึ้นเว็บเมื่อถึงเวลานั้น
   */
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Per-project construction progress: % complete + site photos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress-updates".
 */
export interface ProgressUpdate {
  id: number;
  project: number | Project;
  /**
   * เช่น งวดที่ 5 — พฤษภาคม 2569
   */
  title: string;
  updateDate: string;
  percent: number;
  /**
   * เช่น งานโครงสร้างแล้วเสร็จ เริ่มงานสถาปัตยกรรมภายใน
   */
  description?: string | null;
  photos?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Job postings — untick "active" to close instead of deleting
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  department?: string | null;
  /**
   * เช่น สำนักงานใหญ่ สระบุรี
   */
  location?: string | null;
  employmentType?: ('full-time' | 'part-time' | 'contract') | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Applications from the website — newest first
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  job?: (number | null) | Job;
  coverNote?: string | null;
  cv?: (number | null) | CvFile;
  updatedAt: string;
  createdAt: string;
}
/**
 * Applicant CVs — visible to Admin and Sales/HR only
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cv-files".
 */
export interface CvFile {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Team accounts — only Admin can add/remove users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'sales';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'progress-updates';
        value: number | ProgressUpdate;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: number | JobApplication;
      } | null)
    | ({
        relationTo: 'cv-files';
        value: number | CvFile;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              tagline?: T;
              lead?: T;
              bgImages?: T;
              image?: T;
              imageUrl?: T;
              heroAutoplay?: T;
              heroInterval?: T;
              heroTransition?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              showSearch?: T;
              eyebrowFont?: T;
              eyebrowWeight?: T;
              eyebrowSize?: T;
              eyebrowColor?: T;
              titleFont?: T;
              titleWeight?: T;
              titleSize?: T;
              titleColor?: T;
              taglineFont?: T;
              taglineWeight?: T;
              taglineSize?: T;
              taglineColor?: T;
              leadFont?: T;
              leadWeight?: T;
              leadSize?: T;
              leadColor?: T;
              background?: T;
              paddingY?: T;
              bgColor?: T;
              textOnDark?: T;
              bgImage?: T;
              marginTop?: T;
              marginBottom?: T;
              paddingX?: T;
              gap?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    number?: T;
                    label?: T;
                    id?: T;
                  };
              background?: T;
              paddingY?: T;
              bgColor?: T;
              textOnDark?: T;
              bgImage?: T;
              marginTop?: T;
              marginBottom?: T;
              paddingX?: T;
              gap?: T;
              id?: T;
              blockName?: T;
            };
        featuredProjects?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtitle?: T;
              headingAlign?: T;
              source?: T;
              projects?: T;
              count?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              columns?: T;
              eyebrowFont?: T;
              eyebrowWeight?: T;
              eyebrowSize?: T;
              eyebrowColor?: T;
              headingFont?: T;
              headingWeight?: T;
              headingSize?: T;
              headingColor?: T;
              subtitleFont?: T;
              subtitleWeight?: T;
              subtitleSize?: T;
              subtitleColor?: T;
              background?: T;
              paddingY?: T;
              bgColor?: T;
              textOnDark?: T;
              bgImage?: T;
              marginTop?: T;
              marginBottom?: T;
              paddingX?: T;
              gap?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtitle?: T;
              columns?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              eyebrowFont?: T;
              eyebrowWeight?: T;
              eyebrowSize?: T;
              eyebrowColor?: T;
              headingFont?: T;
              headingWeight?: T;
              headingSize?: T;
              headingColor?: T;
              subtitleFont?: T;
              subtitleWeight?: T;
              subtitleSize?: T;
              subtitleColor?: T;
              background?: T;
              paddingY?: T;
              bgColor?: T;
              textOnDark?: T;
              bgImage?: T;
              marginTop?: T;
              marginBottom?: T;
              paddingX?: T;
              gap?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              content?: T;
              align?: T;
              width?: T;
              eyebrowFont?: T;
              eyebrowWeight?: T;
              eyebrowSize?: T;
              eyebrowColor?: T;
              headingFont?: T;
              headingWeight?: T;
              headingSize?: T;
              headingColor?: T;
              background?: T;
              paddingY?: T;
              bgColor?: T;
              textOnDark?: T;
              bgImage?: T;
              marginTop?: T;
              marginBottom?: T;
              paddingX?: T;
              gap?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              imageSide?: T;
              eyebrow?: T;
              heading?: T;
              content?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              eyebrowFont?: T;
              eyebrowWeight?: T;
              eyebrowSize?: T;
              eyebrowColor?: T;
              headingFont?: T;
              headingWeight?: T;
              headingSize?: T;
              headingColor?: T;
              background?: T;
              paddingY?: T;
              bgColor?: T;
              textOnDark?: T;
              bgImage?: T;
              marginTop?: T;
              marginBottom?: T;
              paddingX?: T;
              gap?: T;
              id?: T;
              blockName?: T;
            };
        columns?:
          | T
          | {
              heading?: T;
              cols?:
                | T
                | {
                    span?: T;
                    image?: T;
                    imageUrl?: T;
                    colHeading?: T;
                    content?: T;
                    headingFont?: T;
                    headingColor?: T;
                    align?: T;
                    id?: T;
                  };
              valign?: T;
              headingFont?: T;
              headingWeight?: T;
              headingSize?: T;
              headingColor?: T;
              background?: T;
              paddingY?: T;
              bgColor?: T;
              textOnDark?: T;
              bgImage?: T;
              marginTop?: T;
              marginBottom?: T;
              paddingX?: T;
              gap?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              columns?: T;
              imageList?: T;
              headingFont?: T;
              headingWeight?: T;
              headingSize?: T;
              headingColor?: T;
              background?: T;
              paddingY?: T;
              bgColor?: T;
              textOnDark?: T;
              bgImage?: T;
              marginTop?: T;
              marginBottom?: T;
              paddingX?: T;
              gap?: T;
              id?: T;
              blockName?: T;
            };
        slider?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              imageList?: T;
              autoplay?: T;
              height?: T;
              headingFont?: T;
              headingWeight?: T;
              headingSize?: T;
              headingColor?: T;
              background?: T;
              paddingY?: T;
              bgColor?: T;
              textOnDark?: T;
              bgImage?: T;
              marginTop?: T;
              marginBottom?: T;
              paddingX?: T;
              gap?: T;
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    year?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              eyebrowFont?: T;
              eyebrowWeight?: T;
              eyebrowSize?: T;
              eyebrowColor?: T;
              headingFont?: T;
              headingWeight?: T;
              headingSize?: T;
              headingColor?: T;
              subtitleFont?: T;
              subtitleWeight?: T;
              subtitleSize?: T;
              subtitleColor?: T;
              background?: T;
              paddingY?: T;
              bgColor?: T;
              textOnDark?: T;
              bgImage?: T;
              marginTop?: T;
              marginBottom?: T;
              paddingX?: T;
              gap?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              text?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              titleFont?: T;
              titleWeight?: T;
              titleSize?: T;
              titleColor?: T;
              textFont?: T;
              textWeight?: T;
              textSize?: T;
              textColor?: T;
              background?: T;
              paddingY?: T;
              bgColor?: T;
              textOnDark?: T;
              bgImage?: T;
              marginTop?: T;
              marginBottom?: T;
              paddingX?: T;
              gap?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  interestProject?: T;
  interestText?: T;
  budget?: T;
  message?: T;
  consentPDPA?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  status?: T;
  zone?: T;
  address?: T;
  tagline?: T;
  description?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        units?: T;
        usableArea?: T;
        landSize?: T;
        bedrooms?: T;
        bathrooms?: T;
        projectValue?: T;
      };
  startingPrice?: T;
  priceTier?: T;
  promoNote?: T;
  coverImage?: T;
  coverAspect?: T;
  coverFit?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  floorPlans?:
    | T
    | {
        name?: T;
        image?: T;
        id?: T;
      };
  map?:
    | T
    | {
        googleMapsUrl?: T;
        lat?: T;
        lng?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        lineId?: T;
        salesEmail?: T;
      };
  videoUrl?: T;
  virtualTourUrl?: T;
  locationFeatures?:
    | T
    | {
        title?: T;
        detail?: T;
        id?: T;
      };
  featured?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  project?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverImage?: T;
  category?: T;
  excerpt?: T;
  content?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress-updates_select".
 */
export interface ProgressUpdatesSelect<T extends boolean = true> {
  project?: T;
  title?: T;
  updateDate?: T;
  percent?: T;
  description?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  department?: T;
  location?: T;
  employmentType?: T;
  description?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  job?: T;
  coverNote?: T;
  cv?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cv-files_select".
 */
export interface CvFilesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Logo, brand color, and contact info — applies to the website on save
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * เว้นว่าง = ใช้โลโก้ NORTHLAND ตัวอักษรเริ่มต้น
   */
  logo?: (number | null) | Media;
  /**
   * โลโก้สีขาว/สว่าง สำหรับวางบนพื้นหลังสีเข้ม — เว้นว่าง = ใช้โลโก้ตัวอักษรขาว
   */
  logoDark?: (number | null) | Media;
  brandColorDark?: string | null;
  brandColor?: string | null;
  secondaryColor1?: string | null;
  secondaryColor2?: string | null;
  secondaryColor3?: string | null;
  bodyFont?:
    | (
        | 'prompt'
        | 'sarabun'
        | 'kanit'
        | 'athiti'
        | 'anuphan'
        | 'ibm-thai'
        | 'montserrat'
        | 'barlow'
        | 'zalando'
        | 'noto-thai'
        | 'noto-serif-thai'
      )
    | null;
  displayFont?:
    | (
        | 'prompt'
        | 'sarabun'
        | 'kanit'
        | 'athiti'
        | 'anuphan'
        | 'ibm-thai'
        | 'montserrat'
        | 'barlow'
        | 'zalando'
        | 'noto-thai'
        | 'cormorant'
        | 'playfair'
        | 'noto-serif-thai'
      )
    | null;
  baseFontSize?: string | null;
  headerPaddingY?: string | null;
  footerPaddingY?: string | null;
  bodyGap?: string | null;
  /**
   * พิมพ์: normal (1200px) / wide (1400px) / full (เต็มจอ)
   */
  containerWidth?: string | null;
  phone?: string | null;
  email?: string | null;
  lineId?: string | null;
  /**
   * เช่น https://lin.ee/xxxx — เว้นว่างได้
   */
  lineUrl?: string | null;
  address?: string | null;
  footerTagline?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  logoDark?: T;
  brandColorDark?: T;
  brandColor?: T;
  secondaryColor1?: T;
  secondaryColor2?: T;
  secondaryColor3?: T;
  bodyFont?: T;
  displayFont?: T;
  baseFontSize?: T;
  headerPaddingY?: T;
  footerPaddingY?: T;
  bodyGap?: T;
  containerWidth?: T;
  phone?: T;
  email?: T;
  lineId?: T;
  lineUrl?: T;
  address?: T;
  footerTagline?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}